
-- Drop tables
DROP TABLE students CASCADE CONSTRAINTS;   
DROP TABLE books CASCADE CONSTRAINTS;
DROP TABLE loans CASCADE CONSTRAINTS;
DROP TABLE fines CASCADE CONSTRAINTS;
DROP TABLE paid_fines CASCADE CONSTRAINTS;

-- Create tables
CREATE TABLE students (
    student_id int GENERATED by default on null as IDENTITY,
    student_name varchar(50),
    email varchar(50),
    course_name varchar(50),
    PRIMARY KEY (student_id)
);

CREATE TABLE books (
    book_id int GENERATED by default on null as IDENTITY,
    book_name varchar(50),
    course_title varchar(50),
    PRIMARY KEY (book_id)
);

CREATE TABLE loans (
    loan_id int GENERATED by default on null as IDENTITY,
    student_id int,
    book_id int,
    date_borrowed date,
    PRIMARY KEY (loan_id),
    FOREIGN KEY (student_id) REFERENCES students(student_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id)
);

CREATE TABLE fines (
    fine_id int GENERATED by default on null as IDENTITY,
    loan_id int,
    amount_owed NUMBER,
    date_issued date,
    PRIMARY KEY (fine_id),
    FOREIGN KEY (loan_id) REFERENCES loans(loan_id)
);

CREATE TABLE paid_fines (
    paid_fine_id int GENERATED by default on null as IDENTITY,
    fine_id int,
    date_paid date,
    PRIMARY KEY (paid_fine_id),
    FOREIGN KEY (fine_id) REFERENCES fines(fine_id)
);

-- Adding test data to the students table
INSERT INTO students (student_name, email, course_name)
VALUES ('student1', 'student1@gmail.com', 'Computer Science');

INSERT INTO students (student_name, email, course_name)
VALUES ('student2', 'student2@gmail.com', 'Psychology');

INSERT INTO students (student_name, email, course_name)
VALUES ('student3', 'student3@gmail.com', 'Criminology');

-- Adding test data to the books table
INSERT INTO books (book_name, course_title)
VALUES ('book1', 'Computer Science');

INSERT INTO books (book_name, course_title)
VALUES ('book2', 'Computer Science');

INSERT INTO books (book_name, course_title)
VALUES ('book3', 'Psychology');

-- Adding test data to the loans table
INSERT INTO loans (student_id, book_id, date_borrowed)
VALUES ('1', '1', TO_DATE('01/01/2023', 'DD/MM/YYYY'));

INSERT INTO loans (student_id, book_id, date_borrowed)
VALUES ('1', '2', TO_DATE('05/01/2023', 'DD/MM/YYYY'));

-- Adding test data to the fines table
INSERT INTO fines (loan_id, amount_owed, date_issued)
VALUES ('1', 20, TO_DATE('29/01/2023', 'DD/MM/YYYY'));

INSERT INTO fines (loan_id, amount_owed, date_issued)
VALUES ('2', 10.50, TO_DATE('29/01/2023', 'DD/MM/YYYY'));

-- Adding test data to the paid_fines table
INSERT INTO paid_fines (fine_id, date_paid)
VALUES ('1', TO_DATE('30/01/2023', 'DD/MM/YYYY'));